# Explicitly define providers to avoid auto-detection issues (e.g. Node)
providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT"
